### ISSUE TITLE
2 Erros: home de usuário que possui evento e área de revisor

### ISSUE THREAD

**Issue by MBaltz** [lmts-ufape/EventosCientificos_ModuloTrabalhos#56]
__Loguei com o user: CoordComissaoOrganizadora__

![image](https://user-images.githubusercontent.com/25617786/105214504-dbd93300-5b2e-11eb-929d-1ae77e991f02.png)

__Outro erro:__

_Alguma rota está chamando um controller que mudou de diretório:_

![image](https://user-images.githubusercontent.com/25617786/105215015-818ca200-5b2f-11eb-9911-423bf0f796f4.png)

**Comment by lmts-ufape** [comment]
Resolvido! Obrigado!
